'use client'

import { useState } from 'react'
import { AlertTriangle, Bell, Check, ChevronRight, CircleDot, Clock3, FileWarning, Menu, ShieldCheck, Terminal, X, Plus, Play, Search, Settings2 } from 'lucide-react'

const nav = ['Overview', 'Agents', 'Playground', 'Workflows', 'Live Monitor', 'Threats', 'Policies', 'Approvals', 'Evaluations', 'Settings']
const events = [
  { time: '09:42:18', agent: 'DevAgent', action: 'read_file', detail: 'package.json', decision: 'ALLOW', risk: 8, tone: 'allow' },
  { time: '09:42:19', agent: 'DevAgent', action: 'search_web', detail: 'documentation', decision: 'ALLOW', risk: 12, tone: 'allow' },
  { time: '09:42:21', agent: 'DevAgent', action: 'execute_command', detail: 'rm -rf ./src', decision: 'BLOCK', risk: 96, tone: 'block' },
  { time: '09:42:24', agent: 'ResearchAgent', action: 'external_request', detail: 'api.example.com', decision: 'REVIEW', risk: 72, tone: 'review' },
]
const agents = [
  ['DevAgent', 'RUNNING', 'LOW', '8', '1,284'], ['ResearchAgent', 'IDLE', 'MEDIUM', '5', '642'], ['CodeAgent', 'BLOCKED', 'HIGH', '11', '327']
]
const threats = [['PI-001', 'Prompt Injection', 'CRITICAL', 'DevAgent', 'User Input', '09:42'], ['TOOL-024', 'Dangerous Tool Call', 'HIGH', 'CodeAgent', 'execute_command', '09:31'], ['SEC-011', 'Sensitive Data Exposure', 'HIGH', 'ResearchAgent', 'Tool Output', '08:54']]

function Logo() { return <div className="logo"><div className="logo-mark"><ShieldCheck size={17} /></div><div><strong>AgentShield</strong><span>AI AGENT SECURITY</span></div></div> }
function Header({ open, setOpen }: { open:boolean; setOpen:(v:boolean)=>void }) { return <header className="topbar"><Logo /><div className="topbar-meta"><span className="env">LOCAL <b>/</b> DEVELOPMENT</span><span className="system"><i /> SYSTEM OPERATIONAL</span><button className="icon-button" aria-label="Notifications"><Bell size={17}/></button></div><button className="menu-button" onClick={()=>setOpen(!open)} aria-label={open?'Close navigation':'Open navigation'}>{open?<X size={22}/>:<Menu size={22}/>}</button></header> }
function Drawer({ open, setOpen, active, setActive }: { open:boolean; setOpen:(v:boolean)=>void; active:string; setActive:(v:string)=>void }) { return open ? <aside className="drawer"><div className="drawer-head"><Logo/><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={20}/></button></div><nav>{nav.map((item,i)=><button className={item===active?'selected':''} key={item} onClick={()=>{setActive(item);setOpen(false)}}><span>{String(i+1).padStart(2,'0')}</span>{item}<ChevronRight size={15}/></button>)}</nav><div className="drawer-foot"><span><i/> Secure runtime active</span><small>AgentShield v0.1 · Open Source</small></div></aside> : null }
function Button({ children, onClick, secondary=false }: { children:React.ReactNode; onClick?:()=>void; secondary?:boolean }) { return <button className={secondary?'control-button secondary':'control-button'} onClick={onClick}>{children}</button> }
function Badge({ children, tone='blue' }: { children:React.ReactNode; tone?:string }) { return <span className={`security-badge ${tone}`}>{children}</span> }
function PageHead({ eyebrow, title, description, action }: { eyebrow:string; title:string; description:string; action?:React.ReactNode }) { return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function Panel({ title, eyebrow, children, className='' }: { title:string; eyebrow?:string; children:React.ReactNode; className?:string }) { return <section className={`panel workspace-panel ${className}`}><div className="panel-head"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div></div>{children}</section> }
function StatusHeader() { return <section className="status-header"><div><span className="eyebrow">SECURITY CONTROL CENTER / OVERVIEW</span><h1>AgentShield Security</h1><p>Your agents are protected.</p></div><div className="protected"><span><i/> PROTECTED</span><small>Last scan 09:42:22</small></div></section> }
function Overview() { return <main className="dashboard"><StatusHeader/><div className="metrics">{[['1,284','THREATS BLOCKED','↑ 12.4%','up'],['18,492','ACTIONS INSPECTED','↑ 8.2%','up'],['03','ACTIVE AGENTS','ALL GUARDED','blue'],['02','PENDING APPROVALS','REQUIRES ACTION','warn']].map(([v,l,m,t])=><div className="metric" key={l}><span>{l}</span><strong>{v}</strong><b className={t}>{m}</b></div>)}</div><div className="dashboard-grid"><Panel title="DevAgent" eyebrow="LIVE AGENT EXECUTION"><div className="agent-context"><Terminal size={16}/><span>AGENT: <b>DevAgent</b></span><span>MODE: <b>GUARDED</b></span><span>UPTIME: <b>02:14:08</b></span></div><div className="event-list">{events.map(e=><div className={`event ${e.tone}`} key={e.time}><time>{e.time}</time><span className="event-action">{e.action} <small>{e.detail}</small></span><span className="event-risk">RISK {String(e.risk).padStart(2,'0')}</span><b>{e.decision}</b></div>)}</div><div className="panel-foot"><span><CircleDot size={13}/> Streaming security events</span><button onClick={()=>{}}>View full monitor <ChevronRight size={14}/></button></div></Panel><Panel title="Nothing executes unseen." eyebrow="DECISION PIPELINE"><div className="decision-flow">{['AI AGENT','TOOL CALL','AGENTSHIELD','SECURITY ANALYSIS','DECISION','EXECUTION'].map((s,i)=><div className="decision-step" key={s}><div className={i===4?'decision-node active':'decision-node'}>{i===4?<Check size={15}/>:i===2?<ShieldCheck size={15}/>:<span>{String(i+1).padStart(2,'0')}</span>}</div><b>{s}</b>{i<5&&<div className="flow-line"/>}</div>)}</div><div className="decision-legend"><span className="allow"><i/> ALLOW</span><span className="review"><i/> REVIEW</span><span className="block"><i/> BLOCK</span></div></Panel><Panel title="Recent threats" eyebrow="THREAT INTELLIGENCE"><ThreatTable compact/></Panel><Panel title="Approval queue 02" eyebrow="HUMAN IN THE LOOP"><ApprovalCard compact/></Panel></div></main> }
function ThreatTable({ compact=false }: { compact?:boolean }) { return <div className={compact?'threat-list':'data-list'}>{threats.map(([id,type,severity,agent,source,time])=><div className="threat-row" key={id}><div className={`severity ${severity.toLowerCase()}`}><AlertTriangle size={14}/></div><div><strong>{type}</strong><span>{id} · {agent} · {source}</span></div><Badge tone={severity==='CRITICAL'?'danger':severity==='HIGH'?'danger':'warn'}>{severity}</Badge><time>{time}</time></div>)}</div> }
function ApprovalCard({ compact=false }: { compact?:boolean }) { return <div className={`approval-card ${compact?'compact':''}`}><div className="approval-top"><FileWarning size={17}/><span>DevAgent wants to execute</span><b>HIGH RISK</b></div><h3>git push origin main</h3><code>Production repository modification</code><p>Risk score: <strong>72 / 100</strong></p><div className="approval-actions"><button className="approve"><Check size={14}/> APPROVE</button><button className="reject"><X size={14}/> DENY</button></div></div> }
function AgentsPage({ setActive }: { setActive:(v:string)=>void }) { const [selected,setSelected]=useState<string|null>(null); return <main className="workspace"><PageHead eyebrow="AGENTS / RUNTIME INVENTORY" title="Agents" description="Manage and monitor AI agents protected by AgentShield." action={<Button onClick={()=>setSelected('new')}><Plus size={14}/> Connect Agent</Button>}/>{selected&&<div className="notice"><span>Agent connection workflow ready.</span><button onClick={()=>setSelected(null)}><X size={14}/></button></div>}<div className="agent-grid">{agents.map(([name,status,risk,tools,actions])=><article className="agent-card" key={name} onClick={()=>setSelected(name)}><div className="card-top"><div className="agent-avatar"><Terminal size={18}/></div><Badge tone={status==='BLOCKED'?'danger':status==='IDLE'?'warn':'success'}>{status}</Badge></div><h2>{name}</h2><div className="agent-risk"><span>RISK LEVEL</span><strong className={risk==='HIGH'?'danger':risk==='MEDIUM'?'warn':'success'}>{risk}</strong></div><div className="agent-stats"><span><b>{tools}</b> TOOLS</span><span><b>{actions}</b> ACTIONS TODAY</span></div><button className="row-link">Open agent <ChevronRight size={14}/></button></article>)}</div>{selected&&selected!=='new'&&<Panel title={`${selected} / Security profile`} eyebrow="AGENT DETAIL"><div className="detail-grid"><div><span className="label">CONNECTED TOOLS</span><p>read_file · search_web · execute_command · write_file</p></div><div><span className="label">PERMISSIONS</span><p>Filesystem read · Network review · Shell approval</p></div><div><span className="label">RECENT DECISION</span><p><Badge tone="danger">BLOCKED</Badge> destructive shell command</p></div></div></Panel>}</main> }
function Playground() { return <main className="workspace"><PageHead eyebrow="PLAYGROUND / POLICY SIMULATION" title="Agent Playground" description="Test agent actions and inspect every security decision in real time." action={<Button><Play size={14}/> Run simulation</Button>}/><div className="playground-grid"><Panel title="Agent configuration" eyebrow="CONFIGURATION"><div className="form-stack"><label>AGENT<select><option>DevAgent</option></select></label><label>MODEL<select><option>Qwen / Local Model</option></select></label><label>SYSTEM INSTRUCTIONS<textarea defaultValue={'You are a coding assistant...'} /></label><fieldset><legend>TOOLS</legend>{['read_file','search_web','execute_command','write_file'].map(t=><label className="check" key={t}><input type="checkbox" defaultChecked/> {t}</label>)}</fieldset></div></Panel><Panel title="Execution stream" eyebrow="LIVE AGENT EXECUTION"><div className="conversation"><div className="chat-line"><span>USER</span><p>Update the project dependencies.</p></div><div className="chat-line agent"><span>AGENT</span><p>I will inspect package.json.</p></div><div className="tool-call"><span>TOOL CALL</span><code>read_file("package.json")</code><Badge tone="success">ALLOWED · RISK 08</Badge></div><div className="tool-call"><span>TOOL CALL</span><code>execute("npm install")</code><Badge tone="success">ALLOWED · RISK 18</Badge></div><div className="tool-call blocked"><span>TOOL CALL</span><code>execute("rm -rf ./src")</code><Badge tone="danger">BLOCKED · RISK 96</Badge></div></div></Panel><Panel title="96 / 100" eyebrow="SECURITY DECISION"><div className="decision-panel"><Badge tone="danger">BLOCK</Badge><h3>High risk action intercepted</h3><ul><li>Destructive filesystem operation</li><li>Irreversible action</li><li>Outside permitted tool policy</li></ul><p>Suggested safer action: <strong>Remove only the obsolete files after confirming their paths.</strong></p><div className="decision-actions"><Button>Allow Once</Button><Button secondary>Block</Button><Button secondary>Require Approval</Button></div></div></Panel></div></main> }
function MonitorPage() { return <main className="workspace"><PageHead eyebrow="LIVE MONITOR / EVENT STREAM" title="Live Security Monitor" description="Every agent action, analyzed and decided at runtime." action={<Badge tone="success">● SYSTEM OPERATIONAL</Badge>}/><div className="filter-bar"><Button secondary><Search size={14}/> Search events</Button>{['All','Allowed','Review','Blocked','Critical'].map(x=><button key={x} className="filter-chip">{x}</button>)}</div><Panel title="Security events" eyebrow="REAL-TIME FEED"><div className="monitor-list">{events.map(e=><div className={`monitor-row ${e.tone}`} key={e.time}><time>{e.time}</time><strong>{e.agent}</strong><code>{e.action}</code><span>{e.detail}</span><Badge tone={e.tone==='block'?'danger':e.tone==='review'?'warn':'success'}>{e.decision}</Badge><b>RISK {e.risk}</b></div>)}</div></Panel></main> }
function Workflows() { const steps=['GitHub Pull Request','Code Agent','Prompt Injection Scan','Secret Detection','Tool Permission Check','Human Approval','Merge']; return <main className="workspace"><PageHead eyebrow="WORKFLOWS / ENFORCEMENT CHAINS" title="Secure Workflows" description="Build deterministic security gates around autonomous execution." action={<Button><Plus size={14}/> Create workflow</Button>}/><Panel title="Code Review Security" eyebrow="ACTIVE WORKFLOW"><div className="workflow"><span className="trigger">TRIGGER</span>{steps.map((s,i)=><div className="workflow-step" key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong><small>{i===2?'AI security scan':i===4?'Permission gate':i===5?'Human decision':'Connected step'}</small>{i<steps.length-1&&<ChevronRight size={16}/>}</div>)}</div></Panel></main> }
function Policies() { const rows=[['Destructive Commands','BLOCK','CRITICAL','All agents'],['External Network Access','REVIEW','HIGH','ResearchAgent'],['Secret Access','BLOCK','CRITICAL','All agents'],['File System Write','REVIEW','MEDIUM','DevAgent'],['Unknown Tools','BLOCK','HIGH','All agents'],['Prompt Injection','BLOCK','CRITICAL','All agents']]; return <main className="workspace"><PageHead eyebrow="POLICIES / ENFORCEMENT ENGINE" title="Security Policies" description="The rules that decide what agents can do." action={<Button><Plus size={14}/> New policy</Button>}/><Panel title="Active policy set" eyebrow="6 POLICIES"><div className="policy-list">{rows.map(([name,action,severity,scope])=><div className="policy-row" key={name}><div><strong>{name}</strong><span>{scope} · severity {severity}</span></div><Badge tone={action==='BLOCK'?'danger':'warn'}>{action}</Badge><button className="toggle on" aria-label={`Toggle ${name}`}><i/></button><Settings2 size={15}/></div>)}</div></Panel></main> }
function ThreatsPage() { return <main className="workspace"><PageHead eyebrow="THREATS / INVESTIGATION" title="Threat Intelligence" description="Investigate attacks and understand why AgentShield intervened."/><Panel title="Threat queue" eyebrow="3 ACTIVE INVESTIGATIONS"><div className="threat-table"><div className="table-head"><span>ID</span><span>TYPE</span><span>SEVERITY</span><span>AGENT</span><span>SOURCE</span><span>TIME</span></div>{threats.map(t=><div className="table-row" key={t[0]}>{t.map((x,i)=><span key={x} className={i===2?'danger':''}>{i===2?<Badge tone="danger">{x}</Badge>:x}</span>)}</div>)}</div></Panel><Panel title="Investigation notes" eyebrow="SELECT A THREAT"><div className="empty-investigation"><AlertTriangle size={24}/><p>Select a threat from the queue to inspect its payload, agent response, and recommended mitigation.</p></div></Panel></main> }
function ApprovalsPage() { return <main className="workspace"><PageHead eyebrow="APPROVALS / HUMAN IN THE LOOP" title="Human Approval" description="Intervene before high-risk agent actions execute."/><div className="approval-grid"><ApprovalCard/><ApprovalCard/></div></main> }
function Evaluations() { return <main className="workspace"><PageHead eyebrow="EVALUATIONS / ADVERSARIAL TESTING" title="Agent Evaluation" description="Run security tests against an agent before it reaches production." action={<Button><Play size={14}/> Run security evaluation</Button>}/><div className="evaluation-summary"><div><span>SECURITY SCORE</span><strong>94<small>/100</small></strong></div><div><span>TESTS</span><b>42</b></div><div><span>PASSED</span><b className="success">39</b></div><div><span>BLOCKED ATTACKS</span><b className="success">37</b></div></div><Panel title="Technical results" eyebrow="LATEST RUN"><div className="policy-list">{['Prompt Injection','Tool Abuse','Data Exfiltration','Privilege Escalation','Malicious Instructions','Unsafe Shell Commands','Unauthorized Network Access'].map((x,i)=><div className="policy-row" key={x}><div><strong>{x}</strong><span>Adversarial test suite / run #0042</span></div><Badge tone={i===2?'warn':'success'}>{i===2?'3 FAILED':'PASSED'}</Badge><span className="muted">{i===2?'72':'100'}%</span></div>)}</div></Panel></main> }
function SettingsPage() { return <main className="workspace"><PageHead eyebrow="SETTINGS / RUNTIME CONFIGURATION" title="Settings" description="Configure how AgentShield protects your agents."/><div className="settings-grid"><Panel title="Security controls" eyebrow="ENFORCEMENT"><div className="settings-list">{['Prompt Injection Detection','Tool Permission Enforcement','Secret Detection','Human Approval','Runtime Monitoring'].map(x=><div key={x}><span>{x}</span><button className="toggle on" aria-label={`Toggle ${x}`}><i/></button></div>)}</div></Panel><Panel title="Model runtime" eyebrow="PROVIDER"><div className="form-stack"><label>MODEL TYPE<select><option>Local / Open Weight</option></select></label><label>PROVIDER<select><option>Ollama</option></select></label><label>MODEL<select><option>Qwen</option></select></label></div></Panel></div></main> }
function App() { const [open,setOpen]=useState(false); const [active,setActive]=useState('Overview'); const page=active==='Overview'?<Overview/>:active==='Agents'?<AgentsPage setActive={setActive}/>:active==='Playground'?<Playground/>:active==='Workflows'?<Workflows/>:active==='Live Monitor'?<MonitorPage/>:active==='Threats'?<ThreatsPage/>:active==='Policies'?<Policies/>:active==='Approvals'?<ApprovalsPage/>:active==='Evaluations'?<Evaluations/>:<SettingsPage/>; return <div className="app"><Header open={open} setOpen={setOpen}/><Drawer open={open} setOpen={setOpen} active={active} setActive={setActive}/>{page}<footer><Logo/><span>Security infrastructure for autonomous AI.</span><span>OPEN SOURCE · 2026</span></footer></div> }

export default App
export { Terminal }
